steps:
  - name: "gcr.io/cloud-builders/gcloud"
    id: "Trigger deploy of EncryptFunction from new zip"
    entrypoint: "/bin/bash"
    args:
      - "-c"
      - |
        gcloud functions deploy NiFiEncryptFunction \
          --runtime go113 \
          --region=europe-west2 \
          --trigger-event=google.storage.object.finalize \
          --trigger-resource=$_NIFI_STAGING_BUCKET \
          --set-env-vars PUBLIC_KEY='./serverless_function_source_code/pkg/encryption/keys/$_ENV-key.gpg',ENCRYPTION_DESTINATION='$_NIFI_BUCKET'
