steps:
  - name: "gcr.io/cloud-builders/gcloud"
    id: "Trigger deploy of EncryptFunction from new zip"
    entrypoint: "/bin/bash"
    args:
      - "-c"
      - |
        gcloud functions deploy NiFiEncryptFunction \
          --gen2 \
          --runtime go122 \
          --region=europe-west2 \
          --entry-point=NiFiEncryptFunction \
          --trigger-event=google.cloud.storage.object.v1.finalized \
          --trigger-resource=$_NIFI_STAGING_BUCKET \
          --set-env-vars PUBLIC_KEY='./serverless_function_source_code/pkg/encryption/keys/$_ENV-key.gpg',ENCRYPTION_DESTINATION='$_NIFI_BUCKET,DDS_URL='$_ENV_DDS_URL'
